export const USER_INFO_FETCH_REQUEST = 'USER_INFO_FETCH_REQUEST';
export const USER_INFO_FETCH_ERROR = 'USER_INFO_FETCH_ERROR';
export const USER_INFO_FETCH_SUCCESS = 'USER_INFO_FETCH_SUCCESS';

export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST';
export const USER_LOGIN_ERROR = 'USER_LOGIN_ERROR';
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';

export const TIME_TRAVEL = 'TIME_TRAVEL';

export const INFO_MESSAGE_SHOW = 'INFO_MESSAGE_SHOW';
export const INFO_MESSAGE_HIDE = 'INFO_MESSAGE_HIDE';

export const ISSUES_AVAILABLE_FETCH_REQUEST = 'ISSUES_AVAILABLE_FETCH_REQUEST';
export const ISSUES_AVAILABLE_FETCH_ERROR = 'ISSUES_AVAILABLE_FETCH_ERROR';
export const ISSUES_AVAILABLE_FETCH_SUCCESS = 'ISSUES_AVAILABLE_FETCH_SUCCESS';

export const ISSUES_WORKED_FETCH_REQUEST = 'ISSUES_WORKED_FETCH_REQUEST';
export const ISSUES_WORKED_FETCH_ERROR = 'ISSUES_WORKED_FETCH_ERROR';
export const ISSUES_WORKED_FETCH_SUCCESS = 'ISSUES_WORKED_FETCH_SUCCESS';

export const ISSUE_SELECTION_START = 'ISSUE_SELECTION_START';
export const ISSUE_SELECTION_CHANGE = 'ISSUE_SELECTION_CHANGE';
export const ISSUE_SELECTION_FINISH = 'ISSUE_SELECTION_FINISH';
export const ISSUE_SELECTION_REVERT = 'ISSUE_SELECTION_REVERT';

export const ISSUE_WORKLOG_DELETE_REQUEST = 'ISSUE_WORKLOG_DELETE_REQUEST';
export const ISSUE_WORKLOG_DELETE_ERROR = 'ISSUE_WORKLOG_DELETE_ERROR';
export const ISSUE_WORKLOG_DELETE_SUCCESS = 'ISSUE_WORKLOG_DELETE_SUCCESS';

export const ISSUE_WORKLOG_ADD_REQUEST = 'ISSUE_WORKLOG_ADD_REQUEST';
export const ISSUE_WORKLOG_ADD_ERROR = 'ISSUE_WORKLOG_ADD_ERROR';
export const ISSUE_WORKLOG_ADD_SUCCESS = 'ISSUE_WORKLOG_ADD_SUCCESS';

export const OTHERS_TOGGLE = 'OTHERS_TOGGLE';

export const SEARCH_CHANGE = 'SEARCH_CHANGE';
export const IMPERSONATED_EMAIL_CHANGE = 'IMPERSONATED_EMAIL_CHANGE';
export const ERROR_HIDE = 'ERROR_HIDE';
